users:

  enableTestUser: ${ENABLE_TEST_USER}
  testUserUsername: ${TEST_USER_USERNAME}
  testUserPassword: ${TEST_USER_PASSWORD}
  testUserEmail: ${TEST_USER_EMAIL}

jmeter:

  jmeterHome: ${JMETER_HOME}
  jmeterProperties: ${JMETER_PROPERTIES}
  jmeterLogOutputDirectory: ${JMETER_LOGS_DIR}

spring:

  groovy:
    template:
      check-template-location: false

  datasource:
    url: ${DATASOURCE_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        dialect.storage_engine: innodb
