icarus:

  functionSourcesDirectory: ${FUNCTION_SOURCES_DIRECTORY:classpath/resources/user_resources}

  reports:
    testCaseResultReportTemplateLocation: ${TEST_CASE_RESULT_REPORT_DIRECTORY:classpath/resources/testCaseResultReportTemplate.rptdesign}
    metricResultReportTemplateLocation: ${METRIC_RESULT_REPORT_DIRECTORY:classpath/resources/metricResultReportTemplate.rptdesign}



security:

  credentialsExpirationPeriod: ${CREDENTIALS_EXPIRATION_PERIOD:355}

  users:

    enableTestUser: ${ENABLE_TEST_USER:false}
    testUserUsername: ${TEST_USER_USERNAME:}
    testUserPassword: ${TEST_USER_PASSWORD:}
    testUserEmail: ${TEST_USER_EMAIL:}



jmeter:

  jmeterHome: ${JMETER_HOME}
  jmeterProperties: ${JMETER_PROPERTIES}
  jmeterLogOutputDirectory: ${JMETER_LOGS_DIR}



terraform:

  stackOutputDirectory: ${STACK_OUTPUT_DIRECTORY:classpath:/resources/terraform/stacks}
  useLocalProviders: ${USE_LOCAL_PROVIDERS:true} # Increases terraform initialization time dramatically
  localProvidersDirectory: ${LOCAL_PROVIDERS_DIRECTORY:classpath:resources/terraform/providers}



spring:

  groovy:
    template:
      check-template-location: false

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB

  datasource:
    url: ${DATASOURCE_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

    hikari:
      initialization-fail-timeout: 0

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

  lifecycle:
    timeout-per-shutdown-phase: 10s



server:
  shutdown: graceful



logging:
  level:
    org.apache.jmeter: ERROR

