security:

  credentialsExpirationPeriod: ${CREDENTIALS_EXPIRATION_PERIOD:355}



  users:

    enableTestUser: ${ENABLE_TEST_USER}
    testUserUsername: ${TEST_USER_USERNAME}
    testUserPassword: ${TEST_USER_PASSWORD}
    testUserEmail: ${TEST_USER_EMAIL}

    functionSourcesDirectory: ${FUNCTION_SOURCES_DIRECTORY:classpath/resources}



jmeter:

  jmeterHome: ${JMETER_HOME}
  jmeterProperties: ${JMETER_PROPERTIES}
  jmeterLogOutputDirectory: ${JMETER_LOGS_DIR}



terraform:

  stackOutputDirectory: ${STACK_OUTPUT_DIRECTORY}
  useLocalProviders: ${USE_LOCAL_PROVIDERS}
  localProvidersDirectory: ${LOCAL_PROVIDERS_DIRECTORY}



spring:

  groovy:
    template:
      check-template-location: false

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB

  datasource:
    url: ${DATASOURCE_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false



logging:
  level:
    org.apache.jmeter: ERROR
